name: sit_in_the_cafeteria
description: "A new Flutter project."
publish_to: "none"
version: 0.9.9

environment:
  sdk: ">=3.4.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_hooks: ^0.20.5
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.1
  flutter_slidable: ^3.1.1
  freezed_annotation: ^2.4.1
  go_router: ^14.2.1
  hooks_riverpod: ^2.5.1
  intl: ^0.19.0
  location: ^6.0.2
  package_info_plus: ^8.0.0
  provider: ^6.1.2
  riverpod_annotation: ^2.3.5
  settings_ui: ^2.0.2
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  riverpod_generator: ^2.4.0
  build_runner: ^2.4.11
  custom_lint: ^0.6.4
  riverpod_lint: ^2.3.10
  freezed: ^2.5.2
  json_annotation: ^4.9.0
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
  assets:
    - lib/src/assets/images/
    - .env

# dart run flutter_native_splash:create
# 768 x 768 以内の画像
flutter_native_splash:
  color: "#011345"
  image: lib/src/assets/images/splash-icon.png
  color_dark: "#011345"
  image_dark: lib/src/assets/images/splash-icon.png
  android_12:
    image: lib/src/assets/images/adaptive-icon-foreground.png
    icon_background_color: "#011345"
    image_dark: lib/src/assets/images/adaptive-icon-foreground.png
    icon_background_color_dark: "#011345"

# flutter pub run flutter_launcher_icons
flutter_launcher_icons:
  android: true
  ios: true
  # size: 512 x 512 くらい
  image_path: "lib/src/assets/images/app-icon.png"
  # size: 上のサイズの50%くらいの背景透過画像

  adaptive_icon_background: "#011345"
  adaptive_icon_foreground: "lib/src/assets/images/adaptive-icon-foreground.png"
